// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using TrandingSystem.Domain.Entities;



namespace TrandingSystem.Infrastructure.Data;

public partial class db23617Context : IdentityDbContext<User, Role, int>
{
    public db23617Context(DbContextOptions<db23617Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Community> Communities { get; set; }

    public virtual DbSet<CommunityMember> CommunityMembers { get; set; }

    public virtual DbSet<ContactInfo> ContactInfos { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<CourseEnrollment> CourseEnrollments { get; set; }

    public virtual DbSet<CourseLecturer> CourseLecturers { get; set; }

    public virtual DbSet<CourseRating> CourseRatings { get; set; }

    public virtual DbSet<LandingPageContent> LandingPageContents { get; set; }

    public virtual DbSet<LiveSession> LiveSessions { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<NotificationChannel> NotificationChannels { get; set; }

    public virtual DbSet<NotificationSetting> NotificationSettings { get; set; }

    public virtual DbSet<NotificationsQueue> NotificationsQueues { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    public virtual DbSet<UsersConnection> UsersConnections { get; set; }

    public virtual DbSet<Video> Videos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfiguration(new Configurations.CategoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CommunityConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CommunityMemberConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ContactInfoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CourseConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CourseEnrollmentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CourseLecturerConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CourseRatingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LandingPageContentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LiveSessionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MessageConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.NotificationChannelConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.NotificationSettingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.NotificationsQueueConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RoleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserSessionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsersConnectionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VideoConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
