// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities;
public partial class Community
{
    public int CommunityId { get; set; }

    public string Title { get; set; }

    public bool? IsDefault { get; set; }

    public int? CourseId { get; set; }

    public bool? IsClosed { get; set; }

    public bool? IsAdminOnly { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<CommunityMember> CommunityMembers { get; set; } = new List<CommunityMember>();

    public virtual Course Course { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}