// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities
{
    public partial class ContactInfo
    {
        public int ContactId { get; set; }

        public string Label { get; set; }

        public string Value { get; set; }

        public DateTime? LastUpdated { get; set; }

        public bool? IsVisible { get; set; }

        public int CreadteBy { get; set; }

        public virtual User CreadteByNavigation { get; set; }
    }
}