// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrandingSystem.Domain.Entities
{
    public partial class CourseLecturer
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CourseLecturerId { get; set; }

        public int CourseId { get; set; }

        public int LecturerId { get; set; }

        public virtual Course Course { get; set; }

        public virtual User Lecturer { get; set; }
    }
}
