// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities
{
    public partial class CourseEnrollment
    {
        public int EnrollmentId { get; set; }

        public int UserId { get; set; }

        public int CourseId { get; set; }

        public DateTime? EnrollmentDate { get; set; }

        public bool IsConfirmed { get; set; }

        // Merged fields from Order:
        public string ReceiptImagePath { get; set; }
        public byte? OrderStatus { get; set; }   // nullable to allow missing data
        public int? ConfirmedBy { get; set; }
        public DateTime? CreatedAt { get; set; } // preserves the original Order.CreatedAt

        public string CashPhoneNum { get; set; }

        public virtual Course Course { get; set; }

        public virtual User User { get; set; }
    }
}