// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities
{
    public partial class LiveSession
    {
        public int SessionId { get; set; }

        public string TitleEN { get; set; }

        public string TitleAR { get; set; }

        public int CourseId { get; set; }

        public string DescriptionEN { get; set; }

        public string DescriptionAR { get; set; }

        public string YoutubeLink { get; set; }

        public DateTime ScheduledAt { get; set; }

        public bool? IsLocked { get; set; }

        public decimal? Cost { get; set; }

        public DateTime? CreatedAt { get; set; }

        public int CreadteBy { get; set; }

        public bool? IsActive { get; set; }

        public virtual Course Course { get; set; }

        public virtual User CreadteByNavigation { get; set; }
    }
}