// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities;
public partial class NotificationChannel
{
    public int ChannelId { get; set; }

    public string ChannelType { get; set; }

    public string Name { get; set; }

    public string SenderName { get; set; }

    public string SenderAddress { get; set; }

    public string Config { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? LastUpdated { get; set; }
}