// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities;
public partial class NotificationSetting
{
    public int SettingId { get; set; }

    public string EventKey { get; set; }

    public bool? SendEmail { get; set; }

    public bool? SendWhatsApp { get; set; }

    public DateTime? LastUpdated { get; set; }
}