// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities
{
    public partial class Order
    {
        public int OrderId { get; set; }

        public int UserId { get; set; }

        public int CourseId { get; set; }

        public string ReceiptImagePath { get; set; }

        public byte OrderStatus { get; set; }

        public int ConfirmedBy { get; set; }

        public DateTime CreatedAt { get; set; }

        public virtual Course Course { get; set; }

        public virtual User User { get; set; }
    }
}