// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities
{
    public partial class Role
    {
        public byte RoleId { get; set; }

        public string RoleName { get; set; }
        public string Test { set; get; }

        public virtual ICollection<User> Users { get; set; } = new List<User>();
    }
}