// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace TrandingSystem.Domain.Entities;
public partial class User : IdentityUser<int>
{
    public string FullName { get; set; }
    public string Mobile { get; set; }
    public DateTime? RegisteredAt { get; set; }
    public bool IsBlocked { get; set; }
    public int RoleId { get; set; } // Changed from byte to int
    public string Address { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual ICollection<CommunityMember> CommunityMembers { get; set; } = new List<CommunityMember>();

    public virtual ICollection<ContactInfo> ContactInfos { get; set; } = new List<ContactInfo>();

    public virtual ICollection<CourseEnrollment> CourseEnrollments { get; set; } = new List<CourseEnrollment>();

    public virtual ICollection<CourseRating> CourseRatings { get; set; } = new List<CourseRating>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<LandingPageContent> LandingPageContents { get; set; } = new List<LandingPageContent>();

    public virtual ICollection<LiveSession> LiveSessions { get; set; } = new List<LiveSession>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<NotificationsQueue> NotificationsQueues { get; set; } = new List<NotificationsQueue>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Role Role { get; set; }

    public virtual ICollection<UserSession> UserSessions { get; set; } = new List<UserSession>();

    public virtual ICollection<UsersConnection> UsersConnections { get; set; } = new List<UsersConnection>();

    public virtual ICollection<Video> Videos { get; set; } = new List<Video>();
}