// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities
{
    public partial class UsersConnection
    {
        public int UserId { get; set; }

        public string ConnId { get; set; }

        public DateTime? ConnecdAt { get; set; }

        public bool? IsOnline { get; set; }

        public virtual User User { get; set; }
    }
}