// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace TrandingSystem.Domain.Entities
{
    [Index(nameof(CourseId), nameof(UserId),nameof(VideoId),nameof(OrderStatus), IsUnique = true)]  // ✅ Unique constraint

    public partial class Video_CourseEnrollment
    {
        public int EnrollmentId { get; set; }

        public int UserId { get; set; }

        public int? CourseId { get; set; }
        public int? VideoId{ get; set; }

        public DateTime? EnrollmentDate { get; set; } //confirmed At 

        public bool IsConfirmed { get; set; }

        // Merged fields from Order:
        public string ReceiptImagePath { get; set; }
        public byte? OrderStatus { get; set; }   // nullable to allow missing data //0 rejected, 1 accepted , 2 pending
        public int? ConfirmedBy { get; set; }

        // Changed from byte to int to match UserId type
        public DateTime? CreatedAt { get; set; } // preserves the original Order.CreatedAt

        public string CashPhoneNum { get; set; }

        public virtual Course Course { get; set; }
        public virtual Video Video { get; set; }

        public virtual User User { get; set; }
    }
}