// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TrandingSystem.Infrastructure.D:\Private_Work\TradingSystem\BackEnd\TradingSystem\TrandingSystem.Domain\Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public partial class CourseConfiguration : IEntityTypeConfiguration<Course>
    {
        public void Configure(EntityTypeBuilder<Course> entity)
        {
            entity.HasKey(e => e.CourseId).HasName("PK__Courses__C92D71A7892BEE8D");

            entity.Property(e => e.CommunityAutoCreate).HasDefaultValue(false);
            entity.Property(e => e.Cost).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.CreateAt).HasColumnType("datetime");
            entity.Property(e => e.DescriptionAR).IsRequired();
            entity.Property(e => e.DescriptionEN).IsRequired();
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsFullyFree).HasDefaultValue(true);
            entity.Property(e => e.TitleAR).IsRequired();
            entity.Property(e => e.TitleEN)
                .IsRequired()
                .IsUnicode(false);

            entity.HasOne(d => d.Category).WithMany(p => p.Courses)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Courses__Categor__6AEFE058");

            entity.HasOne(d => d.CreateByNavigation).WithMany(p => p.Courses)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK__Courses__CreateB__6BE40491");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Course> entity);
    }
}
