// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TrandingSystem.Domain.Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public   class CourseRatingConfiguration : IEntityTypeConfiguration<CourseRating>
    {
        public void Configure(EntityTypeBuilder<CourseRating> entity)
        {
            entity.HasKey(e => e.RatingId).HasName("PK__CourseRa__FCCDF87C8BAB20B6");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseRatings)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CourseRat__Cours__690797E6");

            entity.HasOne(d => d.User).WithMany(p => p.CourseRatings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CourseRat__UserI__69FBBC1F");

 
        }

     }
}
