// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TrandingSystem.Domain.Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public  class CourseLecturerConfiguration : IEntityTypeConfiguration<CourseLecturer>
    {
        public void Configure(EntityTypeBuilder<CourseLecturer> entity)
        {
            entity.HasNoKey();

            entity.HasOne(d => d.Course).WithMany()
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CourseLec__Cours__671F4F74");

            entity.HasOne(d => d.Lecturer).WithMany()
                .HasForeignKey(d => d.LecturerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CourseLec__Lectu__681373AD");

 
        }

     }
}
