// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TrandingSystem.Domain.Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public   class LandingPageContentConfiguration : IEntityTypeConfiguration<LandingPageContent>
    {
        public void Configure(EntityTypeBuilder<LandingPageContent> entity)
        {
            entity.HasKey(e => e.ContactId).HasName("PK__LandingP__5C66259B582FB7B6");

            entity.ToTable("LandingPageContent");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SectionNameAR).HasMaxLength(100);
            entity.Property(e => e.SectionNameEN)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.CreadteByNavigation).WithMany(p => p.LandingPageContents)
                .HasForeignKey(d => d.CreadteBy)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__LandingPa__Cread__6CD828CA");

 
        }

 
    }
}
