// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TrandingSystem.Domain.Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public   class LiveSessionConfiguration : IEntityTypeConfiguration<LiveSession>
    {
        public void Configure(EntityTypeBuilder<LiveSession> entity)
        {
            entity.HasKey(e => e.SessionId).HasName("PK__LiveSess__C9F49290E808C758");

            entity.Property(e => e.Cost).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.DescriptionAR).IsRequired();
            entity.Property(e => e.DescriptionEN).IsRequired();
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsLocked).HasDefaultValue(false);
            entity.Property(e => e.ScheduledAt).HasColumnType("datetime");
            entity.Property(e => e.TitleAR).IsRequired();
            entity.Property(e => e.TitleEN)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.YoutubeLink).IsUnicode(false);

            entity.HasOne(d => d.Course).WithMany(p => p.LiveSessions)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__LiveSessi__Cours__6DCC4D03");

            entity.HasOne(d => d.CreadteByNavigation).WithMany(p => p.LiveSessions)
                .HasForeignKey(d => d.CreadteBy)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__LiveSessi__Cread__6EC0713C");

 
        }

     }
}
