// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TrandingSystem.Domain.Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public   class NotificationSettingConfiguration : IEntityTypeConfiguration<NotificationSetting>
    {
        public void Configure(EntityTypeBuilder<NotificationSetting> entity)
        {
            entity.HasKey(e => e.SettingId).HasName("PK__Notifica__54372B1DF745D745");

            entity.Property(e => e.EventKey).HasMaxLength(100);
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SendEmail).HasDefaultValue(true);
            entity.Property(e => e.SendWhatsApp).HasDefaultValue(false);

 
        }

     }
}
