// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TrandingSystem.Domain.Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public partial class NotificationsQueueConfiguration : IEntityTypeConfiguration<NotificationsQueue>
    {
        public void Configure(EntityTypeBuilder<NotificationsQueue> entity)
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E124C231CEE");

            entity.ToTable("NotificationsQueue");

            entity.Property(e => e.Channel).HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SentAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("pending");
            entity.Property(e => e.Subject).HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.NotificationsQueues)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Notificat__UserI__719CDDE7");

 
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NotificationsQueue> entity);
    }
}
