// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Reflection.Emit;
using TrandingSystem.Domain.Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public   class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__1788CC4C1041235A");

            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Mobile)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RegisteredAt).HasColumnType("datetime");
            entity.Property(e => e.Address).HasMaxLength(250);


            entity.Property(u => u.RegisteredAt)
        .HasDefaultValueSql("GETDATE()");
            //entity.HasOne(d => d.Role).WithMany(p => p.Users)
            //    .HasForeignKey(d => d.RoleId)
            //    .OnDelete(DeleteBehavior.ClientSetNull)
            //    .HasConstraintName("FK__Users__RoleId__74794A92");


        }

     }
}
