// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TrandingSystem.Infrastructure.D:\Private_Work\TradingSystem\BackEnd\TradingSystem\TrandingSystem.Domain\Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public partial class UsersConnectionConfiguration : IEntityTypeConfiguration<UsersConnection>
    {
        public void Configure(EntityTypeBuilder<UsersConnection> entity)
        {
            entity.HasKey(e => new { e.UserId, e.ConnId }).HasName("PK_Compist");

            entity.Property(e => e.ConnId).HasMaxLength(200);
            entity.Property(e => e.ConnecdAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UsersConnections)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsersConn__UserI__756D6ECB");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsersConnection> entity);
    }
}
