// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TrandingSystem.Domain.Entities;
using TrandingSystem.Infrastructure.Data;

namespace TrandingSystem.Infrastructure.Data.Configurations
{
    public   class Video_CourseEnrollmentConfiguration : IEntityTypeConfiguration<Video_CourseEnrollment>
    {
        public void Configure(EntityTypeBuilder<Video_CourseEnrollment> entity)
        {

            entity.ToTable("VideoCourseEnrollments");

            entity.HasKey(e => e.EnrollmentId).HasName("PK__CourseEn__7F68771BB07A50C4");

            entity.Property(e => e.EnrollmentDate).HasColumnType("datetime");

            // New mappings
            entity.Property(e => e.ReceiptImagePath)
                  .HasMaxLength(500)
                  .IsUnicode(false)
                  .IsRequired(false);

            entity.Property(e => e.OrderStatus)
                  .HasColumnType("tinyint")
                  .IsRequired(false);

            entity.Property(e => e.ConfirmedBy)
                  .IsRequired(false);

            entity.Property(e => e.CreatedAt)
                  .HasColumnType("datetime")
                  .IsRequired(false);

            entity.HasOne(d => d.Course).WithMany(p => p.CourseEnrollments)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__CourseEnr__Cours__65370702");

            entity.HasOne(d => d.User).WithMany(p => p.CourseEnrollments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__CourseEnr__UserI__662B2B3B");

        }

     }
}
